# <font color='black'><center><center></font> 
![title](img/All.png) 
# <font color='white'><center><center></font> 
# <font><center>Artificial Intelligence<center></font>
## <font ><center>CA4: MACHINE LEARNING<center></font>
## <center>Teacher: Dr. Fadaei<center>
### <center>Student Name: Mohammadali Shakerdargah<center>
### <center>Student Number: 810098002<center>

### <font>Purpose:</font>
    In this project we are going to use "scikit-library" to perform machine learning algorithms on given data so that we can fit a model to estimate each vehicle's price.
    
### <font>What  we did in this Project:</font>
    In this project we are going to had a training dataset and a test data set to evaluate our model we used "Naive Bayes" to build a classifier model to predict the category of a book using a description and name of the book

In [2]:
!nvidia-smi -L

GPU 0: Tesla T4 (UUID: GPU-2a6c729d-f51a-7433-cbf3-f6f4cb0b3151)

In [1]:
!pip install hazm
!pip install https://github.com/sobhe/hazm/archive/master.zip --upgrade
!pip install arabic-reshaper
!pip install python-bidi

Requirement already satisfied: hazm in c:\users\mn\anaconda3\lib\site-packages (0.7.1)
Requirement already satisfied: nltk==3.4 in c:\users\mn\anaconda3\lib\site-packages (from hazm) (3.4)
Requirement already satisfied: six in c:\users\mn\anaconda3\lib\site-packages (from nltk==3.4->hazm) (1.15.0)
Requirement already satisfied: singledispatch in c:\users\mn\anaconda3\lib\site-packages (from nltk==3.4->hazm) (0.0.0)
Collecting https://github.com/sobhe/hazm/archive/master.zip
  Using cached https://github.com/sobhe/hazm/archive/master.zip
Requirement already satisfied: nltk==3.4 in c:\users\mn\anaconda3\lib\site-packages (from hazm==0.7.1) (3.4)
Requirement already satisfied: six in c:\users\mn\anaconda3\lib\site-packages (from nltk==3.4->hazm==0.7.1) (1.15.0)
Requirement already satisfied: singledispatch in c:\users\mn\anaconda3\lib\site-packages (from nltk==3.4->hazm==0.7.1) (0.0.0)
Requirement already satisfied: arabic-reshaper in c:\users\mn\anaconda3\lib\site-packages (2.1.3)
Requirement already satisfied: future in c:\users\mn\anaconda3\lib\site-packages (from arabic-reshaper) (0.18.2)
Requirement already satisfied: setuptools in c:\users\mn\anaconda3\lib\site-packages (from arabic-reshaper) (52.0.0.post20210125)
Requirement already satisfied: python-bidi in c:\users\mn\anaconda3\lib\site-packages (0.4.2)
Requirement already satisfied: six in c:\users\mn\anaconda3\lib\site-packages (from python-bidi) (1.15.0)

In [2]:
from __future__ import unicode_literals
from hazm import *
import pandas as pd
from numpy import *
import math
import operator
import matplotlib.pyplot as plt
import arabic_reshaper
from bidi.algorithm import get_display
import sklearn
from sklearn import feature_selection
from sklearn import metrics
from sklearn.preprocessing import MinMaxScaler

In [3]:
# from google.colab import drive
# drive.mount('/content/drive')

In [4]:
# data = pd.read_csv("/content/drive/MyDrive/Colab_Documents/AI/CA4/vehicles.csv")
data = pd.read_csv("vehicles.csv")
data

,brand,category,created_at,description,image_count,mileage,price,title,year
0,NaN,heavy,Tuesday 07PM,سریال 43j$NUMبدون شکستگی سه حلقه لاستیک نو یک ...,4,NaN,-1,لودر کاتر پیلار 950,NaN
1,سایر,light,Wednesday 04AM,دوگانه ال پی جی بیمه با تخفیف دارد \nتودوزی نو...,3,180000.0,-1,پاترول شش سیلندر چهار درب,1366
2,پژو ۴۰۵::Peugeot 405,light,Wednesday 11AM,پژو 2000فنی تازه تعمیر بدنه بدون خطو خش تخیف ب...,0,290000.0,8500000,پژو مدل 81 مشکی,1381
3,نیسان::Nissan,light,Wednesday 01PM,سلام.\nماشین کاملا سالم همه چی فابریک متور زد ...,3,175000.0,19500000,پاترول 2در,1372
4,سمند::Samand,light,Thursday 07AM,سمند ال ایکس بدون رنگ تمامی سرویس ها انجام شده...,4,80000.0,23900000,سمند دوگانه کارخانه,1391
...,...,...,...,...,...,...,...,...,...
130438,NaN,heavy,Wednesday 03PM,بادسان فوق بیرنگ سفید رنگ بیمه تابرج 3.96 تخفی...,2,NaN,48000000,بادسان 8b14 مدل83,NaN
130439,NaN,heavy,Wednesday 06PM,باسلام .تراکتورازصفری دست خودم بوده.سالم.ودارا...,4,NaN,-1,تراکتورگلدونی ۲۳۸ایتالیا,NaN
130440,سمند::Samand,light,Wednesday 06PM,ماشینم تصادفیه با خریدار توافق میکنم سر قیمتش,3,20000.0,-1,خودرو سمند تصادفی مدل92,1392
130441,پراید صندوق‌دار::Pride,light,Thursday 03PM,سند۲ برگ،بیمه تا برج$NUMتخفیفات بیمه 15 سال،مع...,4,123000.0,6900000,پراید 79 بسیار سالم,1379
130442,پراید صندوق‌دار::Pride,light,Friday 04PM,پراید دوگانه کارخانه میباشد و کم کارکرد.روکش ....,3,43000.0,17400000,پراید دوگانه کارخانه مدل93,1393

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130443 entries, 0 to 130442
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   brand        120451 non-null  object
 1   category     130443 non-null  object
 2   created_at   130443 non-null  object
 3   description  130443 non-null  object
 4   image_count  130443 non-null  int64
 5   mileage      120451 non-null  float64
 6   price        130443 non-null  int64
 7   title        130443 non-null  object
 8   year         120451 non-null  object
dtypes: float64(1), int64(2), object(6)
memory usage: 9.0+ MB

# Phase 1: Preprocessing and Visualization

- First I got rid of those NAN rows. 
- Then, I changed brands from categorical to numerical values (We only had 26 specific brands). 
- After erasing NAN rows and changing brands from categorical to numerical, I decided to cleanse my data. In order to cleanse data I used "hazm" library.
    - it is formal that it is better to work with root of each word. It tells us that prefixes and postfixes are not that necessary for us to participate them in our process.And sometimes they may even reduce our accuracy because all versions of a word are telling us the same thing and almost same info,So we will use 2 methods called "Stemming" and "lemmatization". these two methods share the same goal, and the goal is to remove unnecessary prefixes and postfixes from a word. I prefered to use "lemmatization" because found it beter to use so we won't have (آسمان -> آسم) . It works
        - lemmatizer.lemmatize('می‌روم') -> 'رفت#رو'
    - I could have gone with "Stemming" too and it works like this: 
        - like this: stemmer.stem('کتاب‌ها') -> 'کتاب'
- Then, I tried to change category of the cars into numerical which containes only light cars -> 0
- I scaled "Mileage" with MinMaxScaler so that we wouldn't have our data in a  big range.

In [6]:
data = data[pd.notnull(data['brand'])]
data = data.reset_index(drop=True)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120451 entries, 0 to 120450
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   brand        120451 non-null  object
 1   category     120451 non-null  object
 2   created_at   120451 non-null  object
 3   description  120451 non-null  object
 4   image_count  120451 non-null  int64
 5   mileage      120451 non-null  float64
 6   price        120451 non-null  int64
 7   title        120451 non-null  object
 8   year         120451 non-null  object
dtypes: float64(1), int64(2), object(6)
memory usage: 8.3+ MB

In [7]:
def brandCategorizer(data, brand, categories):
    for i in range(len(data[brand])):
        brand_i = data[brand][i]
        if(brand_i in categories):
            data[brand][i] = categories.get(brand_i)
    return data

In [ ]:
uniqueCategories = data['brand'].unique()
categories ={}
for i in range(len(uniqueCategories)):
    categories[uniqueCategories[i]] = i
for category in categories:
    print("Mapped: ",category," -> ", categories.get(category))
data = brandCategorizer(data, 'brand', categories)
data

Mapped:  سایر  ->  0
Mapped:  پژو ۴۰۵::Peugeot 405  ->  1
Mapped:  نیسان::Nissan  ->  2
Mapped:  سمند::Samand  ->  3
Mapped:  ام‌وی‌ام::MVM  ->  4
Mapped:  پراید صندوق‌دار::Pride  ->  5
Mapped:  پراید هاچ‌بک::Pride  ->  6
Mapped:  پژو پارس::Peugeot Pars  ->  7
Mapped:  پژو ۲۰۶‍::Peugeot 206  ->  8
Mapped:  پیکان::Peykan  ->  9
Mapped:  وانت  ->  10
Mapped:  پژو روآ / آر‌دی::RD/ROA  ->  11
Mapped:  پژو ۲۰۶‍ صندوق‌دار::Peugeot 206  ->  12
Mapped:  تیبا::Tiba  ->  13
Mapped:  زانتیا::Citroen Xantia  ->  14
Mapped:  کیا::Kia  ->  15
Mapped:  رنو::Renault  ->  16
Mapped:  رانا::Runna  ->  17
Mapped:  دوو::Daewoo  ->  18
Mapped:  هیوندای (غیره)::Hyundai  ->  19
Mapped:  تندر ۹۰::Tondar 90  ->  20
Mapped:  تویوتا::Toyota  ->  21
Mapped:  لیفان::Lifan  ->  22
Mapped:  بنز::Mercedes-Benz  ->  23
Mapped:  هیوندای سوناتا::Hyundai Sonata  ->  24
Mapped:  بی‌ام‌و::BMW  ->  25

<ipython-input-7-781bada87f7e>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[brand][i] = categories.get(brand_i)

In [12]:
def dataCleanse(df,col):
    normalizer = Normalizer()
    lemmatizer = Lemmatizer() 
    for i in range(len(df[col])):
        df[col][i] = normalizer.normalize(df[col][i])
            
    punctuations = set('''!()-[]{};:'"\,٬٫،<>./?@#$%٪^&*×ـ+=_~.؟؛«»|…''') #Set of unnecessary punctuations
    for i in range(len(df[col])):
        without_punctuations = ""
        for char in df[col][i]:
            if(char not in punctuations):
                without_punctuations = without_punctuations + char
        df[col][i] = word_tokenize(without_punctuations)
        
    stops = set(stopwords_list()) #List of unnecessary words
    for i in range(len(df[col])):
        wordsWithoutStops = []
        for j in range(len(df[col][i])):
            if(df[col][i][j] not in stops):
                wordsWithoutStops.append(lemmatizer.lemmatize(df[col][i][j]))
        df[col][i] = wordsWithoutStops
    return df

In [13]:
data_cleansed = dataCleanse(data, 'description')
data_cleansed = dataCleanse(data_cleansed, 'title')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [14]:
data_cleansed

       brand category  ...                            title  year
0          0    light  ...            [پاترول, سیلندر, درب]  1366
1          1    light  ...              [پژو, مدل, ۸۱, مشک]  1381
2          2    light  ...                    [پاترول, ۲در]  1372
3          3    light  ...          [سمند, دوگانه, کارخانه]  1391
4          1    light  ...                [پژو, ۴۰۵, مدل۸۴]  1384
...      ...      ...  ...                              ...   ...
120446     5    light  ...            [پراید, مدل, ۸۴, رنگ]  1384
120447     1    light  ...                       [۴۰۵, slx]  1395
120448     3    light  ...      [خودرو, سمند, تصادف, مدل۹۲]  1392
120449     5    light  ...                [پراید, ۷۹, سالم]  1379
120450     5    light  ...  [پراید, دوگانه, کارخانه, مدل۹۳]  1393

[120451 rows x 9 columns]

In [15]:
def categorizer(data, brand, categories):
    for i in range(len(data[brand])):
        brand_i = data[brand][i]
        if(brand_i in categories):
            data[brand][i] = categories.get(brand_i)
    return data

In [16]:
unique_Categories_cars = data_cleansed['category'].unique()
categories_cars ={}
for i in range(len(unique_Categories_cars)):
    categories_cars[unique_Categories_cars[i]] = i
for category in categories_cars:
    print("Mapped: ",category," -> ", categories_cars.get(category))
data_cleansed = categorizer(data_cleansed, 'category', categories_cars)
data_cleansed

Mapped:  light  ->  0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

       brand category  ...                            title  year
0          0        0  ...            [پاترول, سیلندر, درب]  1366
1          1        0  ...              [پژو, مدل, ۸۱, مشک]  1381
2          2        0  ...                    [پاترول, ۲در]  1372
3          3        0  ...          [سمند, دوگانه, کارخانه]  1391
4          1        0  ...                [پژو, ۴۰۵, مدل۸۴]  1384
...      ...      ...  ...                              ...   ...
120446     5        0  ...            [پراید, مدل, ۸۴, رنگ]  1384
120447     1        0  ...                       [۴۰۵, slx]  1395
120448     3        0  ...      [خودرو, سمند, تصادف, مدل۹۲]  1392
120449     5        0  ...                [پراید, ۷۹, سالم]  1379
120450     5        0  ...  [پراید, دوگانه, کارخانه, مدل۹۳]  1393

[120451 rows x 9 columns]

In [17]:
MMScaler = MinMaxScaler()
data_cleansed[['mileage']] = MMScaler.fit_transform(data_cleansed[['mileage']])
data_cleansed

       brand category  ...                            title  year
0          0        0  ...            [پاترول, سیلندر, درب]  1366
1          1        0  ...              [پژو, مدل, ۸۱, مشک]  1381
2          2        0  ...                    [پاترول, ۲در]  1372
3          3        0  ...          [سمند, دوگانه, کارخانه]  1391
4          1        0  ...                [پژو, ۴۰۵, مدل۸۴]  1384
...      ...      ...  ...                              ...   ...
120446     5        0  ...            [پراید, مدل, ۸۴, رنگ]  1384
120447     1        0  ...                       [۴۰۵, slx]  1395
120448     3        0  ...      [خودرو, سمند, تصادف, مدل۹۲]  1392
120449     5        0  ...                [پراید, ۷۹, سالم]  1379
120450     5        0  ...  [پراید, دوگانه, کارخانه, مدل۹۳]  1393

[120451 rows x 9 columns]

In [18]:
data_cleansed_withOut_price = data_cleansed.drop(columns = ['price'])
data_cleansed_withOut_price

       brand category  ...                            title  year
0          0        0  ...            [پاترول, سیلندر, درب]  1366
1          1        0  ...              [پژو, مدل, ۸۱, مشک]  1381
2          2        0  ...                    [پاترول, ۲در]  1372
3          3        0  ...          [سمند, دوگانه, کارخانه]  1391
4          1        0  ...                [پژو, ۴۰۵, مدل۸۴]  1384
...      ...      ...  ...                              ...   ...
120446     5        0  ...            [پراید, مدل, ۸۴, رنگ]  1384
120447     1        0  ...                       [۴۰۵, slx]  1395
120448     3        0  ...      [خودرو, سمند, تصادف, مدل۹۲]  1392
120449     5        0  ...                [پراید, ۷۹, سالم]  1379
120450     5        0  ...  [پراید, دوگانه, کارخانه, مدل۹۳]  1393

[120451 rows x 8 columns]